sudo: false
language: node_js
node_js:
- node
- lts/*
script:
- npm run test
deploy:
  provider: npm
  skip_cleanup: true
  email: vajuoff.1@gmail.com
  api_key:
    secure: JgJj9yhUlNbxjHuHNkA6BEpA98lOTczVECVWaUR8TpQdfANw61VRYyfLfLB0mUxF1uDxiCdHVxpLMEGkz1IpVzaMTQsgeYkqtIrZsGdsFa5vTjQp8lVueVZz1q+2a6Mf4HF3jXQqnOgloMao4hQAmUDmVspQqUyfJkIamzGaEbXvdmwLgkaZmEuBqQ6CF+wamkF1T3rFPSyQGwlw95Z1+lR94GC4V2I50QIoo0iMFY425DdPl+dL8C66On9WUMOQP2+lj2xd1IEXkbU3QcVhDZWX2J+s2S7i0/SurGsftRf7FFSFXcbUi7dneuWiN35G2UF+RAriNMsBX5okA3pPRmCpNC269IU1tMtSEeWLLu7Eua8nlN9Duu8Wg8oZXKYBKGkDpGAngJe6BijBR01PRn/oKSRZqgqLWP6hvIPu6MUokhxnblWb59ni79Poudpo3Y/bULzrLsg32xj+wxIceWvCCbt1o4LU//e3GPKWrwgP/5w3VjuiYU6ZY2UEYF/u4/jvauz4fon6648LKFebOXBK++CczPZzYulw97Q/j5mshCY16TFi1Z+9HVCm77UGe0NEhRN2Z5bAj+LxTRyqmHkXd67sl0bufxWTxFDSL2hGaDXQ7J60pXRY90fTXGAv1n6rCTXGDjhx5T+BuDimWV90upHKBxg2xjo+XA7UDLQ=
  on:
    node_js: lts/*
    tags: true
    branch: master
after_deploy: echo 'deploying to npm!'
